steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/storygrow-api:$COMMIT_SHA', '.']
  
  # Push the Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/storygrow-api:$COMMIT_SHA']
  
  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'storygrow-api'
      - '--image'
      - 'gcr.io/$PROJECT_ID/storygrow-api:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - |
        GEMINI_API_KEY=${_GEMINI_API_KEY},
        GCP_PROJECT_ID=$PROJECT_ID,
        API_HOST=0.0.0.0,
        API_PORT=8080
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--max-instances'
      - '10'

# Substitutions for environment variables
substitutions:
  _GEMINI_API_KEY: 'your_gemini_api_key_here'

timeout: '1200s'

# Options
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'