name: storygrow
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - nodejs=20
  - pip:
    # Backend dependencies
    - fastapi==0.95.0
    - uvicorn==0.21.1
    - google-generativeai==0.7.2
    - python-dotenv==1.0.0
    - pillow==9.5.0
    - psycopg2-binary==2.9.9
    - google-cloud-sql-python-connector==0.10.0
    - pydantic==1.10.7
    - python-multipart==0.0.6
    - aiofiles==23.2.1
    # Testing
    - pytest==7.4.0
    - pytest-asyncio==0.21.0